#!/usr/bin/env python3
"""Module 1-async_comprehension

This module contains the `async_comprehension` coroutine function, which
uses an asynchronous list comprehension to collect 10 random floating-point
numbers generated by the `async_generator` function.
"""
from typing import List


async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Collects 10 random floats from async_generator using async comprehension

    Returns:
        List[float]: A list of 10 random floating-point numbers.
    """
    random_numbers = [number async for number in async_generator()]
    return random_numbers
